CREATE TABLE app_user (
                          id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username    VARCHAR(64) UNIQUE NOT NULL,
                          email       VARCHAR(255) UNIQUE NOT NULL,
                          password    VARCHAR(255) NOT NULL,
                          role_type   VARCHAR(20) NOT NULL DEFAULT 'ROLE_USER',
                          created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          deleted_at  TIMESTAMP DEFAULT NULL
);

CREATE TABLE post (
                      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id     BIGINT NOT NULL,
                      title       VARCHAR(200) NOT NULL,
                      content     CLOB NOT NULL,
                      created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      updated_at  TIMESTAMP DEFAULT NULL,
                      deleted_at  TIMESTAMP DEFAULT NULL,
                      CONSTRAINT fk_post_app_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE INDEX idx_app_user_active
    ON app_user(deleted_at);

CREATE INDEX idx_post_app_user_active_created
    ON post(user_id, deleted_at, created_at);

CREATE INDEX idx_post_active_created
    ON post(deleted_at, created_at);

CREATE INDEX idx_post_title
    ON post(title);
